# Generated by Django 4.2.5 on 2023-11-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(name="Test",),
    ]
