# Generated by Django 4.2.5 on 2023-09-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_remove_menuitem_category"),
    ]

    operations = [
        migrations.DeleteModel(name="Category",),
    ]
